name: conda
description: Publish to Anaconda
inputs:
  tag:
    description: 'Commit / Branch / Tag / SHA to checkout'
    required: false
    default: ''
  dry-run:
    description: 'Dry run'
    required: false
    default: false
  override:
    description: 'Override'
    required: false
    default: true
  password: 
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: 0
      ref: ${{ inputs.tag }}
  - uses: conda-incubator/setup-miniconda@v2
    with:
      auto-activate-base: true
      activate-environment: ""
  - name: Install conda-build
    shell: bash -el {0}
    run: |
      conda install -n base conda-build anaconda-client
  - name: Build
    shell: bash -el {0}
    run: |
      cd .conda
      conda build -c conda-forge -c pytorch --output-folder . .
  - name: Publish
    if: (!inputs.dry-run)
    shell: bash -el {0}
    env: 
      OVERRIDE: ${{ inputs.override }}
    run: |
      [[ "${OVERRIDE}" == "true" ]] && FORCE="--force" || FORCE=""
      anaconda upload ${FORCE} jitfields 
