name: Test package and publish to PyPi

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Commit / Branch / Tag / SHA to checkout'
        required: false
        default: ''
      publish:
        description: 'Publish'
        required: false
        default: 'auto'
        type: choice
        options:
          - 'auto'
          - 'none'
          - 'pypi'
          - 'test'
          - 'test+pypi'
      test:
        description: 'Run tests'
        required: false
        default: 'needs'
        type: choice
        options:
          - 'yes'
          - 'no'
          - 'needs'
      python-version:
        description: 'Python version'
        required: false
        default: '3.7'
#  push:
#    branches: [ main ]
#  release

jobs:
  test:
    if: inputs.test != 'no'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.7"
            pytorch-version: "1.8"
          - python-version: "3.10"
            pytorch-version: "2.0"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          python-version: ${{ matrix.python-version }}
          pytorch-version: ${{ matrix.pytorch-version }}
          tag: ${{ inputs.tag }}

  publish:
    if: |
      inputs.test == 'needs' && 
      inputs.publish != 'none' && 
      (inputs.publish != 'auto' || 
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')))
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          python-version: ${{ inputs.python-version }}
          publish: ${{ inputs.publish }}
          password-pypi: ${{ secrets.pypi_token }}
          password-test: ${{ secrets.test_pypi_token }}
          tag: ${{ inputs.tag }}

  publish-only:
    if: |
      inputs.test != 'needs'  && 
      inputs.publish != 'none' &&
      (inputs.publish != 'auto' || 
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          python-version: ${{ inputs.python-version }}
          publish: ${{ inputs.publish }}
          password-pypi: ${{ secrets.pypi_token }}
          password-test: ${{ secrets.test_pypi_token }}
          tag: ${{ inputs.tag }}
