name: Test package and publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Commit / Branch / Tag / SHA to checkout'
        required: false
        default: ''
      test:
        description: 'Run tests'
        required: false
        default: true
        type: boolean
      publish:
        description: 'Publish'
        required: false
        default: 'none'
        type: choice
        options:
          - 'none'
          - 'pypi'
          - 'test'
          - 'conda'
          - 'dryconda'
          - 'test+pypi'
          - 'pypi+conda'
          - 'test+pypi+conda'
      python-version:
        description: 'Python version'
        required: false
        default: '3.7'

jobs:
  test:
    if: inputs.test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.7"
            pytorch-version: "1.8"
          - python-version: "3.10"
            pytorch-version: "2.0"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          python-version: ${{ matrix.python-version }}
          pytorch-version: ${{ matrix.pytorch-version }}
          tag: ${{ inputs.tag }}

  publish:
    if: inputs.test && inputs.publish != 'none'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pypi
        if: |
          ${{ contains(inputs.publish, 'pypi') }} || 
          ${{ contains(inputs.publish, 'test') }}
        with:
          python-version: ${{ inputs.python-version }}
          publish: ${{ inputs.publish }}
          tag: ${{ inputs.tag }}
          pypi-password: ${{ secret.PYPI_TOKEN }}
          test-password: ${{ secret.TEST_PYPI_TOKEN }}
      - uses: ./.github/actions/conda
        if: ${{ contains(inputs.publish, 'conda') }}
        with:
          tag: ${{ inputs.tag }}
          dry_run: contains(inputs.publish, 'dry')
          password: ${{ secret.ANACONDA_TOKEN }}

  publish-only:
    if: (!inputs.test) && inputs.publish != 'none'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pypi
        if: |
          ${{ contains(inputs.publish, 'pypi') }} || 
          ${{ contains(inputs.publish, 'test') }}
        with:
          python-version: ${{ inputs.python-version }}
          publish: ${{ inputs.publish }}
          tag: ${{ inputs.tag }}
          pypi-password: ${{ secret.PYPI_TOKEN }}
          test-password: ${{ secret.TEST_PYPI_TOKEN }}
      - uses: ./.github/actions/conda
        if: ${{ contains(inputs.publish, 'conda') }}
        with:
          tag: ${{ inputs.tag }}
          dry_run: contains(inputs.publish, 'dry')
          password: ${{ secret.ANACONDA_TOKEN }}
